USE ads;

DELETE FROM books;

ALTER TABLE books AUTO_INCREMENT = 1;

INSERT INTO books (name, author, release_date, image, genre, developer, description)
VALUES ('Vidurnaktį sningant', 'Karen Swan', '2022', 'vidurnakti_sningant.jpg', 'Grožinė literatūra', 'Tyto alba',
        'Romano „Vidurnaktį sningant" veiksmas iš smėlingųjų Amerikos ir Portugalijos paplūdimių skaitytojus nukelia į žiemos stebuklų kupinas Austrijos Alpes. Prieš keletą metų banglenčių varžybose įvykęs nelaimingas atsitikimas, tragiškai pasibaigęs Kito priešininkui, sugriauna nesuskaičiuojamais laimėjimais pažymėtą vyro karjerą. Nors Kitas akimirksniu visuomenės pripažįstamas kaltu dėl nutikusios nelaimės, jis pats niekada taip ir nepapasakojo, kas iš tiesų nutiko tą lemtingą dieną.
        Pasiryžusi išsiaiškinti tikrąją įvykių priežastį, Kloverė išvyksta į snieguotąsias Austrijos Alpes, praleisti romantiškiausio metų laiko kartu su jos nekenčiančiu vyru – juk būtent ji atsakinga už sužlugdytą Kito karjerą.'),
       ('Aštuntas gyvenimas', 'Nino Haratischwili', '2022', 'Astuntas_gyvenimas.jpg', 'Grožinė literatūra', 'Alma littera', 'Romanas „Aštuntas gyvenimas (Brilkai)" sukėlė didelį šurmulį literatūros pasaulyje, sulaukė teigiamo kritikų įvertinimo, o skaitytojų visame pasaulyje buvo pramintas literatūros klasikos „Vėjo nublokšti" gruziniškąja versija. Iš Gruzijos (Sakartvelo) kilusios autorės vokiečių kalba parašytai istorinei šeimos dramai suteiktas ne vienas Vokietijos literatūrinis apdovanojimas, o jos vertimas į anglų kalbą 2020 m. pateko į Tarptautinės Bookerio premijos ilgąjį sąrašą.'),
       ('Užkariauta širdis', 'Dani Collins', '2022', 'Uzkariauta_sirdis.jpg', 'Grožinė literatūra', 'Svajonių knygos', 'Daug kartų nesėkmingai bandžiusi susirasti Poną Tobulybę, paprasta bibliotekininkė Hana Myks nusprendė: metas pačiai imtis iniciatyvos ir kurti šeimą. Netrukus, stebuklingai pastojusi, sužinojo, kad kūdikis, kurio ji laukiasi, – būsimas Bakio sosto paveldėtojas... Šeichas Akinas Sarafas toli gražu nėra tobulas vyras. Išsiaiškinęs, kad jo miręs brolis yra būsimo kūdikio tėvas, Akinas nutaria atsivežti Haną į savo rūmus ir su ja susituokti! Apie vedybas iš meilės negali būti nė kalbos. Tačiau laisva nepažabojamos dvasios Hana pamažu ima užkariauti šeicho širdį.')
        ,
       ('Marmiai. Draugystės magija', 'Indrė Pavilonytė', '2021', 'Marmiai_Draugystes_magija.jpg', 'Literatūra vaikams', 'Alma littera', 'Tą ūkuose paskendusią naktį marmiai Liu ir Aga iš Martvudo girios nusprendė patyrinėti ežere plūduriuojančią salą ir ten atrado kur kas daugiau nei nuotykį. Paslaptingai dingstantys daiktai, ežero pabaisa, širdį virpinanti pažintis su Žaliaskruosčiu ir nuoširdus apkabinimas, darantis tikrus stebuklus!'),
       ('Spragtukas', 'The Nutcracker', '2021', 'Spragtukas.jpg', 'Literatūra vaikams', 'Baltos lankos', 'Klasika tapusią pasaką apie Spragtuką lydi kerinti Piotro Čaikovskio muzika. Susitikimai su knygele neabejotinai taps mažylių laukiamiausia kiekvienos dienos akimirka. Pasinerkite į stebuklų pasaulį!'),

       ('SVEIKATOS DĖSNIAI: penki žingsniai, kaip įveikti ligą ir tapti sveikesniam', 'Robert Zembroski', '2019', 'sveikatos_desniai.jpg', 'Sveika gyvensena', 'Alma littera', 'Užklupus sunkiai ligai ir sutrikus gyvenimo ritmui, imame gailėtis netausoję savo sveikatos ir susimąstome, ar ne per vėlu ko nors imtis. Gera žinia ta, kad sveikatą galima atkurti. Kad ir kokią diagnozę išgirdote, nevalia susitaikyti ir viską palikti spręsti gydytojams. Jūsų pareiga – padėti kūnui atsigauti. Kaip tą padaryti, atskleidžia vėžį įveikęs ir po daugybės chemoterapijos kursų atsitiesęs funkcinės medicinos specialistas dr. Robertas Zembroskis.'),
       ('Energijos paradoksai: ką daryti, kai apleidžia jėgos', 'Steven R. Gundry', '2022', 'Energijos-paradoksai.jpg', 'Sveika gyvensena', 'Alma littera', 'Dr. Gundryʼio nuomone, su nuolatiniu nuovargiu kovojantys žmonės beveik visada turi kai ką bendra: žarnyne prasidėjusį ir išplitusį uždegimą. Šis uždegimas padidina riziką susirgti autoimuninėmis ligomis, sutrikdo medžiagų apykaitą ir išeikvoja brangias energijos atsargas. Autorius pateikia naujus įrodymus apie mikrobiomo vaidmenį gaminant arba, atvirkščiai, sunaudojant energiją ir siūlo priemones, padedančias užgesinti uždegimą.'),

       ('SAULĖTA VIRTUVĖ: saldumynų knyga. ', 'Asta Černė', '2022', 'sauleta_virtuve.jpg', 'Receptų knygos', 'BALTO leidybos namai', 'Asta Černė– knygų ir populiaraus maisto tinklaraščio „Saulėta virtuvė" autorė, maisto fotografė. Prieš trylika metų maisto gaminimą atradusi kaip praturtinantį pomėgį, iki šiol dalijasi paprastais, žemiškais receptais. Knygoje jų rasite daugiau nei šimtą: smaližių pusryčiams, jaukiems savaitgalio pabuvimams, šeimos šventėms, mažiems pasilepinimams. Vieni desertai kvies pažinti pasaulio skonius, kiti– prisiminimais grįžti į vaikystę.'),
       ('Kartu: paprasti receptai šeimai ir draugams', 'Jamie Oliver', '2022', 'Kartu.jpg', 'Receptų knygos', 'Alma littera', 'Daugiau kaip 120 įdomių ir paprastų receptų – „Kartu“ padės jums sukurti neįtikėtinų patiekalų, kuriais galėsite dalintis su mylimais žmonėmis.'),
       ('Nuo pirmo kąsnio', 'Medeina Andriulienė', '2022', 'Nuo_pirmo_kasnio.jpg', 'Receptų knygos', 'Alma littera', '„Iš savo patirties žinau, kad primaitinimo pradžioje tėvams psichologiškai sunkiausia suprasti, jog vaikas turi ne pasisotinti, o susipažinti su maistu, naujais skoniais ir tyrinėti skirtingas tekstūras. Jis vis dar pasisotina mamos pienu arba mišinuku, o kietas maistas yra tik pirmoji pažintis, kuri neturėtų kelti streso, būtų smagi ir lėta. Čia ne traukinys, tikrai visur suspėsite, o įgūdžiai, kuriuos šiuo laikotarpiu suformuosite savo atžalai, niekur nedings visą gyvenimą."'),

       ('Instinktai: kaip mus veikia instinktai ir kaip išmokti juos nukreipti savo naudai', 'Rebecca Heiss', '2022', 'Instinktai.jpg', 'Psichologija', 'Alma littera', 'Kiekvienoje gyvenimo srityje – nuo verslo iki asmeninių santykių ar sveikatos – mūsų elgesį veikia instinktai, kurių paskirtis kadaise buvo padėti mums išlikti pasaulyje, pilname pavojų. Tie patys instinktai kliudo mums siekti sėkmės dabar – įvairovės kupiname pasaulyje su daugybe galimų pasirinkimo variantų ir beveik neribotomis galimybėmis žmonėms kontaktuoti vieniems su kitais.'),
       ('Atsparumas stresui', 'Dr. Sam Akbar', '2022', 'atsparumasstresui.jpg', 'Psichologija', 'Briedis', 'Kasdien daugybė žmonių susiduria su stresu, bet pristinga įgūdžių tinkamai reaguoti ir įveikti gyvenimo siunčiamus iššūkius. Visgi gera žinia ta, kad kovoti su stresu galima išmokti.

        Susitvarkykite su mintimis. Susidorokite su emocijomis. Sukaupkite dėmesį į tai, kas jums gyvenime visų svarbiausia.

        Ilgametė klinikinė psichologė dr. Sam Akbar parodys, kaip viso to pasiekti, pateikdama labai konkrečių ir profesionalių patarimų. Šioje knygoje sužinosite, kaip veikia mūsų smegenys, kaip jos valdo emocijas ir sudėtingus minčių procesus, taip pat išmoksite save užjausti ir naujai pažvelgti į pasaulį.'),
       ('Nuostabus protas: išsamus asmenybės tobulinimo kursas', 'Henrik Fexeus', '2022', 'nuostabus-protas.jpg', 'Psichologija', 'Alma littera', 'Ši knyga – tarsi šuolis tramplinu į mažai ištyrinėtas proto gelmes. Henrikas Fexeusas, žinomas Švedijos lektorius, vienas geriausių kūno kalbos žinovų visame pasaulyje, įtaigiai demonstruoja, kokios elastingos žmogaus smegenys ir kokių fantastiškų rezultatų galime pasiekti atlikdami paprasčiausias treniruotes.');


